name: Bug report
description: Create a report to help us improve
title: "[Bug]: "
labels: ["bug"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        A clear and concise description of what the bug is.

  - type: input
    id: description
    attributes:
      label: Bug Description
      description: Provide a detailed description of the bug.
      placeholder: Describe the bug here
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: List the steps to reproduce the bug.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: input
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: Describe what you expected to happen.
      placeholder: Describe the expected behavior here
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots or videos to help explain your problem.
      placeholder: Add screenshots or videos here
    validations:
      required: false

  - type: dropdown
    id: install_type
    attributes:
      label: HeyForm Installation
      description: Select the type of HeyForm installation.
      options:
        - heyform.net
        - self hosted
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: Provide the version or commit SHA if self hosted.
      placeholder: e.g., commit sha
    validations:
      required: true

  - type: dropdown
    id: desktop_os
    attributes:
      label: Desktop OS
      description: Select the desktop operating system.
      options:
        - Windows
        - macOS
        - Linux
        - NA/Other
    validations:
      required: true

  - type: dropdown
    id: desktop_browser
    attributes:
      label: Desktop Browser
      description: Provide the browser used on desktop.
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Opera
    validations:
      required: false

  - type: input
    id: desktop_version
    attributes:
      label: Desktop Browser Version
      description: |
        Provide the browser version used on desktop.
        [Find your browser version](https://www.whatismybrowser.com/)
      placeholder: e.g., 100
    validations:
      required: false

  - type: dropdown
    id: mobile_device
    attributes:
      label: Mobile Device
      description: Provide the mobile device used.
      options:
        - iPhone
        - iPad
        - Android phone
        - Android tablet
        - Other
    validations:
      required: false

  - type: dropdown
    id: mobile_os
    attributes:
      label: Mobile OS
      description: |
        Provide the mobile operating system.
        [Find your Android version](https://support.google.com/android/answer/7680439?hl=en)
        [Find your iOS version](https://support.apple.com/en-us/HT201685)
      options:
        - iOS
        - Android
        - Other
    validations:
      required: false

  - type: dropdown
    id: mobile_browser
    attributes:
      label: Mobile Browser
      description: Provide the browser used on mobile.
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Opera
        - Other
    validations:
      required: false

  - type: input
    id: mobile_version
    attributes:
      label: Mobile Browser Version
      description: |
        Provide the browser version used on mobile.
        [Find your browser version](https://www.whatismybrowser.com/)
      placeholder: e.g., 100
    validations:
      required: false
